import 'package:flutter/material.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox5widget/generated/GeneratedButterchickenWidget.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox5widget/generated/GeneratedDownload251Widget1.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox5widget/generated/GeneratedDownload292Widget.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox5widget/generated/GeneratedL9QUUZoF_400x4001Widget.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox5widget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox5widget/generated/GeneratedTefal15minutesflateasyfishdishesanythingispossible1Widg1.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox5widget/generated/GeneratedSalamonWidget.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox5widget/generated/GeneratedDownload291Widget.dart';

/* Frame iPhone 11 Pro / X - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 176.0,
                height: 128.0,
                child:
                    GeneratedTefal15minutesflateasyfishdishesanythingispossible1Widg1(),
              ),
              Positioned(
                left: 231.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 142.0,
                child: GeneratedDownload251Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 57.0,
                child: GeneratedSalamonWidget(),
              ),
              Positioned(
                left: 201.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 38.0,
                child: GeneratedButterchickenWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 653.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 84.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 1.0,
                top: 433.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 71.0,
                child: GeneratedDownload291Widget(),
              ),
              Positioned(
                left: 285.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 71.0,
                child: GeneratedDownload292Widget(),
              ),
              Positioned(
                left: -26.0,
                top: -48.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 399.0,
                child: GeneratedL9QUUZoF_400x4001Widget(),
              )
            ]),
      ),
    ));
  }
}
