import 'package:flutter/material.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox9widget/generated/GeneratedE9e4jQFXMAM4Ymr1Widget1.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox9widget/generated/GeneratedGroup1Widget3.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox9widget/generated/GeneratedPORKCHOPSAREHARAMWidget.dart';

/* Frame iPhone 11 Pro / X - 9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 325.0,
                child: GeneratedE9e4jQFXMAM4Ymr1Widget1(),
              ),
              Positioned(
                left: 36.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 278.0,
                child: GeneratedPORKCHOPSAREHARAMWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 664.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 84.0,
                child: GeneratedGroup1Widget3(),
              )
            ]),
      ),
    ));
  }
}
