import 'package:flutter/material.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox1widget/generated/GeneratedIPhone11ProMax1Widget.dart';

/* Frame iPhone 11 Pro / X - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedIPhone11ProX3Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -19.0,
                  top: -42.0,
                  right: null,
                  bottom: null,
                  width: 414.0,
                  height: 896.0,
                  child: GeneratedIPhone11ProMax1Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
