import 'package:flutter/material.dart';

/* Slice Slice 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSlice1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
