import 'package:flutter/material.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox10widget/generated/GeneratedGroup1Widget4.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox10widget/generated/GeneratedComebacksoonWidget.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox10widget/generated/GeneratedL9QUUZoF_400x4001Widget2.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox10widget/generated/GeneratedThanksforplayingWidget.dart';

/* Frame iPhone 11 Pro / X - 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX10Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -12.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 399.0,
                child: GeneratedL9QUUZoF_400x4001Widget2(),
              ),
              Positioned(
                left: 56.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 125.0,
                child: GeneratedThanksforplayingWidget(),
              ),
              Positioned(
                left: -1.0,
                top: 587.0,
                right: null,
                bottom: null,
                width: 379.0,
                height: 71.0,
                child: GeneratedComebacksoonWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 696.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 66.0,
                child: GeneratedGroup1Widget4(),
              )
            ]),
      ),
    ));
  }
}
