import 'package:flutter/material.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox6widget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox6widget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox6widget/generated/GeneratedE9e4jQFXMAM4Ymr1Widget.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox6widget/generated/GeneratedPOPTARTSAREHARAMWidget.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox6widget/generated/GeneratedGroup1Widget1.dart';

/* Frame iPhone 11 Pro / X - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 325.0,
                child: GeneratedE9e4jQFXMAM4Ymr1Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 379.90655517578125,
                height: 1.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 256.0,
                top: 461.0,
                right: null,
                bottom: null,
                width: 301.8774719238281,
                height: 1.0,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 209.0,
                child: GeneratedPOPTARTSAREHARAMWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 664.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 84.0,
                child: GeneratedGroup1Widget1(),
              )
            ]),
      ),
    ));
  }
}
