import 'package:flutter/material.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox7widget/generated/Generated646969301Widget.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox7widget/generated/GeneratedHalal1Widget1.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox7widget/generated/GeneratedDownload301Widget.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox7widget/generated/Generated__opt__aboutcom__coeus__resources__content_migration__s.dart';

/* Frame iPhone 11 Pro / X - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 352.0,
                child: GeneratedHalal1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 458.0,
                right: null,
                bottom: null,
                width: 159.0,
                height: 155.0,
                child: Generated646969301Widget(),
              ),
              Positioned(
                left: 226.0,
                top: 461.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 149.0,
                child: GeneratedDownload301Widget(),
              ),
              Positioned(
                left: 80.0,
                top: 671.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 141.0,
                child:
                    Generated__opt__aboutcom__coeus__resources__content_migration__s(),
              )
            ]),
      ),
    ));
  }
}
