import 'package:flutter/material.dart';
import 'package:flutterapp/sshsapp/generatediphone13promax1widget/generated/GeneratedDownload281Widget1.dart';
import 'package:flutterapp/sshsapp/generatediphone13promax1widget/generated/GeneratedPlayWidget7.dart';
import 'package:flutterapp/sshsapp/generatediphone13promax1widget/generated/GeneratedHelloIvebeeninvitedtoapartybutidontknowifthefoodthereis1.dart';
import 'package:flutterapp/sshsapp/generatediphone13promax1widget/generated/GeneratedRectangle4Widget5.dart';

/* Frame iPhone 13 Pro Max - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 289.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 637.0,
                              child: GeneratedDownload281Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 7.0,
                              right: null,
                              bottom: null,
                              width: 510.0,
                              height: 277.0,
                              child:
                                  GeneratedHelloIvebeeninvitedtoapartybutidontknowifthefoodthereis1(),
                            ),
                            Positioned(
                              left: 69.0,
                              top: 800.0,
                              right: null,
                              bottom: null,
                              width: 291.0,
                              height: 66.0,
                              child: GeneratedRectangle4Widget5(),
                            ),
                            Positioned(
                              left: 162.0,
                              top: 814.0,
                              right: null,
                              bottom: null,
                              width: 133.0,
                              height: 42.0,
                              child: GeneratedPlayWidget7(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
