import 'package:flutter/material.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox8widget/generated/Generated646969301Widget1.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox8widget/generated/GeneratedDownload292Widget1.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox8widget/generated/GeneratedShawarmaWidget.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox8widget/generated/GeneratedChickenWidget.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox8widget/generated/GeneratedGroup1Widget2.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox8widget/generated/GeneratedL9QUUZoF_400x4001Widget1.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox8widget/generated/Generated__opt__aboutcom__coeus__resources__content_migration__s1.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox8widget/generated/GeneratedDownload291Widget1.dart';

/* Frame iPhone 11 Pro / X - 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -24.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 371.0,
                child: GeneratedL9QUUZoF_400x4001Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 428.0,
                right: null,
                bottom: null,
                width: 159.0,
                height: 155.0,
                child: Generated646969301Widget1(),
              ),
              Positioned(
                left: 1.0,
                top: 433.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 71.0,
                child: GeneratedDownload291Widget1(),
              ),
              Positioned(
                left: 188.0,
                top: 442.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 141.0,
                child:
                    Generated__opt__aboutcom__coeus__resources__content_migration__s1(),
              ),
              Positioned(
                left: 285.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 71.0,
                child: GeneratedDownload292Widget1(),
              ),
              Positioned(
                left: 4.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 172.0,
                height: 57.0,
                child: GeneratedShawarmaWidget(),
              ),
              Positioned(
                left: 202.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 57.0,
                child: GeneratedChickenWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 106.0,
                child: GeneratedGroup1Widget2(),
              )
            ]),
      ),
    ));
  }
}
