import 'package:flutter/material.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox2widget/generated/GeneratedHalal1Widget.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox2widget/generated/GeneratedDownload251Widget.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox2widget/generated/GeneratedDownload261Widget.dart';
import 'package:flutterapp/sshsapp/generatediphone11prox2widget/generated/GeneratedTefal15minutesflateasyfishdishesanythingispossible1Widg.dart';

/* Frame iPhone 11 Pro / X - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 314.0,
                child: GeneratedHalal1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 425.0,
                right: null,
                bottom: null,
                width: 176.0,
                height: 128.0,
                child:
                    GeneratedTefal15minutesflateasyfishdishesanythingispossible1Widg(),
              ),
              Positioned(
                left: 231.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 142.0,
                child: GeneratedDownload251Widget(),
              ),
              Positioned(
                left: 116.0,
                top: 601.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 136.0,
                child: GeneratedDownload261Widget(),
              )
            ]),
      ),
    ));
  }
}
